import React from 'react';
import Navbar from '../../components/Navbar';

const AdvisorAgreement = () => {
    return (
        <>
            <Navbar />
            <div style={{ maxWidth: '800px', margin: '40px auto', padding: '20px', backgroundColor: '#fff', borderRadius: '8px', boxShadow: '0 4px 6px rgba(0,0,0,0.05)' }}>
                <h1 style={{ textAlign: 'center', marginBottom: '30px', color: '#111' }}>Advisor Agreement</h1>

                <div style={{ lineHeight: '1.6', color: '#444' }}>
                    <h2 style={{ fontSize: '20px', color: '#0b3c91', marginTop: '20px' }}>1. Appointment</h2>
                    <ul style={{ paddingLeft: '20px', marginBottom: '15px' }}>
                        <li>This Agreement governs the relationship between TRIONA Realty Group and the registered Advisor.</li>
                        <li>The Advisor agrees to operate under the Property Lead Advisor Model.</li>
                    </ul>

                    <h2 style={{ fontSize: '20px', color: '#0b3c91', marginTop: '20px' }}>2. Nature of Role</h2>
                    <ul style={{ paddingLeft: '20px', marginBottom: '15px' }}>
                        <li>The Advisor is an independent associate and not an employee, partner, or agent of the company.</li>
                        <li>The Advisor's Role is limited to submitting genuine buyer/seller leads.</li>
                    </ul>

                    <h2 style={{ fontSize: '20px', color: '#0b3c91', marginTop: '20px' }}>3. Commission Structure </h2>
                    <ul style={{ paddingLeft: '20px', marginBottom: '15px' }}>
                        <li>Commission shall be paid only on successfully closed transacions.</li>
                        <li>Buying and Selling commission percentages will be applicable as per the Advisor's selected registration plan at the time of deal closure.</li>
                    </ul>

                    <h2 style={{ fontSize: '20px', color: '#0b3c91', marginTop: '20px' }}>4. Referral Benefits</h2>
                    <ul style={{ paddingLeft: '20px', marginBottom: '15px' }}>
                        <li>If an Advisor refer a new member, the refering Advisor shall receive 50% of the referred member's registation fee , One time incentive.</li>
                        <li>In addition, the refering advisor shall receive 0.1% lifetime commission on every successfully closed property deal generated by their direct referred member.</li>
                        <li>The 0.1% lifetime commission applies to both buyig and selling transactions of direct team members only .</li>
                    </ul>

                    <h2 style={{ fontSize: '20px', color: '#0b3c91', marginTop: '20px' }}>5. Payment Terms</h2>
                    <ul style={{ paddingLeft: '20px', marginBottom: '15px' }}>
                        <li>Commission payments will be processed on the 10th of the following month after successfulldeal closure.</li>
                        <li>If the 10th falls on a weekend or government holiday, payment will be processed on the next working business day.</li>
                    </ul>

                    <h2 style={{ fontSize: '20px', color: '#0b3c91', marginTop: '20px' }}>6. Advisor Responsibilities</h2>
                    <ul style={{ paddingLeft: '20px', marginBottom: '15px' }}>
                        <li>Submit accurate and genuine lead information.</li>
                        <li>Maintain ethical business conduct.</li>
                        <li>Not misrepresent company authority or brand.</li>
                    </ul>

                    <h2 style={{ fontSize: '20px', color: '#0b3c91', marginTop: '20px' }}>7. Prohibited Activities</h2>
                    <ul style={{ paddingLeft: '20px', marginBottom: '15px' }}>
                        <li>Submission  of fake leads.</li>
                        <li>Bypassing company process.</li>
                        <li>Unauthorized use of branding or confident data.</li>
                    </ul>

                    <h2 style={{ fontSize: '20px', color: '#0b3c91', marginTop: '20px' }}>8. Termination</h2>
                    <ul style={{ paddingLeft: '20px', marginBottom: '15px' }}>
                        <li>The company reserves the right to suspend or terminate the Advisor for policy Violations.</li>
                        <li>Termination may result in forfeiture of pending incentives in case of fraud or misconduct.</li>
                    </ul>


                    <h2 style={{ fontSize: '20px', color: '#0b3c91', marginTop: '20px' }}>9. No Income Guarantee</h2>
                    <ul style={{ paddingLeft: '20px', marginBottom: '15px' }}>
                        <li>The Company does not guarantee fixed income or assured earnings.</li>
                        <li>Earning depend on performance, succesful deal closures, and market conditions.</li>
                    </ul>

                    <h2 style={{ fontSize: '20px', color: '#0b3c91', marginTop: '20px' }}>10. Governing Law</h2>
                    <ul style={{ paddingLeft: '20px', marginBottom: '15px' }}>
                        <li>This Agreement shal be governed by the laws of india.</li>
                        <li>Jurisdiction shall be Bhopal, Madhya Pradesh.</li>
                    </ul>

                    <h2 style={{ fontSize: '20px', color: '#0b3c91', marginTop: '20px' }}>11. Acceptance</h2>
                    <ul style={{ paddingLeft: '20px', marginBottom: '15px' }}>
                        <li>By registering and participating in TRIONA Realty Group, the Advisors agree to all terms stated in this Agreement.</li>
                    </ul>


                </div>
            </div>
        </>
    );
};

export default AdvisorAgreement;
